services:
  database:
    image: "postgres:18beta3-alpine3.22"
    environment:
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: aestheticsbydrhendler
    ports:
      - 5432:5432
